import { Button, Center, Container } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Sitsigenerator v2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center style={{ height: "100vh" }}>
        <Center style={{ width: 200, flexDirection: "column" }}>
          <Link href="/timer" passHref>
            <Button m={10} fullWidth>
              Aloita
            </Button>
          </Link>
          <Link href="/settings" passHref>
            <Button m={10} fullWidth>
              Asetukset
            </Button>
          </Link>
        </Center>
      </Center>
    </Container>
  );
};

export default Home;
