import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "../components/Link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/timer">Aloita</Link>
      <Link href="/settings" bgColor="#3DB2FF">
        Asetukset
      </Link>
    </div>
  );
};

export default Home;
